# Generated by Django 6.0.1 on 2026-01-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('nome_aluno', models.CharField(max_length=100)),
                ('idade_aluno', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
