# Generated by Django 6.0.1 on 2026-01-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='idade_aluno',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='nome_aluno',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='idade_aluna',
            field=models.PositiveIntegerField(default=0, verbose_name='Idade da aluna(o)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome_aluna',
            field=models.CharField(default=0, max_length=100, verbose_name='Nome da aluna(o)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(verbose_name='Data da aula'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(verbose_name='Horário da aula'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_responsavel',
            field=models.CharField(max_length=100, verbose_name='Nome do responsável'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
