# Generated by Django 6.0.1 on 2026-02-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.aula', verbose_name='Aula escolhida'),
        ),
    ]
